/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import MetodosJY.TextPrompt;
import Modelo.Config;
import Modelo.Eventos;
import Modelo.LoginDAO;
import Modelo.Productos;
import Modelo.ProductosDao;
import Modelo.login;
import static Vista.Sistema.isValid;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author yanch
 */
public class Registro extends javax.swing.JFrame {

    int xMouse, yMouse;

    Sistema sistema = new Sistema();
    login lg = new login();
    LoginDAO login = new LoginDAO();
    Eventos event = new Eventos();

    /**
     * Creates new form Registro
     */
    public Registro() {

        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/sistema.png")));
        TextPrompt Correo = new TextPrompt("Correo del Usuario", txtCorreo);
        Correo.setForeground(Color.LIGHT_GRAY);
        TextPrompt Pass = new TextPrompt("Contraseña del Usuario", txtPass);
        Pass.setForeground(Color.LIGHT_GRAY);
        TextPrompt Nombre = new TextPrompt("Nombre del Usuario", txtNombre1);
        Nombre.setForeground(Color.LIGHT_GRAY);
        TextPrompt Cedula = new TextPrompt("Cedula del Usuario", txtCedula);
        Cedula.setForeground(Color.LIGHT_GRAY);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPRegistrar = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtCedula = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        btnIniciar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnexit = new javax.swing.JPanel();
        txtexit1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        JPRegistrar.setBackground(new java.awt.Color(255, 51, 255));
        JPRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iniciar.png"))); // NOI18N
        JPRegistrar.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 86));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Correo Electrónico:");
        JPRegistrar.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 51, 255));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        JPRegistrar.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 226, 30));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Contraseña:");
        JPRegistrar.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtPass.setBackground(new java.awt.Color(255, 51, 255));
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(null);
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });
        JPRegistrar.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 226, 30));

        txtCedula.setBackground(new java.awt.Color(255, 51, 255));
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.setBorder(null);
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        JPRegistrar.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 226, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Cédula:");
        JPRegistrar.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Cargo:");
        JPRegistrar.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        cbxRol.setBorder(null);
        JPRegistrar.add(cbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 226, 30));

        btnIniciar.setBackground(new java.awt.Color(0, 0, 255));
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Registrar");
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        JPRegistrar.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 93, 34));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        JPRegistrar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        JPRegistrar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        JPRegistrar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 10));

        btnexit.setBackground(new java.awt.Color(255, 0, 0));
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnexitMouseDragged(evt);
            }
        });
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnexitMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnexitMousePressed(evt);
            }
        });

        txtexit1.setBackground(new java.awt.Color(0, 130, 190));
        txtexit1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtexit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit1.setText("X");
        txtexit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexit1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnexitLayout = new javax.swing.GroupLayout(btnexit);
        btnexit.setLayout(btnexitLayout);
        btnexitLayout.setHorizontalGroup(
            btnexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnexitLayout.createSequentialGroup()
                .addComponent(txtexit1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnexitLayout.setVerticalGroup(
            btnexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtexit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPRegistrar.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 40, 30));

        header.setBackground(new java.awt.Color(255, 51, 255));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        JPRegistrar.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 40));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Nombre:");
        JPRegistrar.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtNombre1.setBackground(new java.awt.Color(255, 51, 255));
        txtNombre1.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre1.setBorder(null);
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });
        txtNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombre1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre1KeyTyped(evt);
            }
        });
        JPRegistrar.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 226, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        JPRegistrar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    //BOTON REGISTRAR
    
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if (txtCedula.getText().equals("") || txtCorreo.getText().equals("") || txtPass.getPassword().equals("")) {
            JOptionPane.showMessageDialog(null, "Todo los campos son requeridos");
        } else {
            Config conf = new Config();
            ProductosDao proDao = new ProductosDao();
            conf = proDao.BuscarDatos();

            String cedula = txtCedula.getText();
            String correo = txtCorreo.getText();
            String pass = String.valueOf(txtPass.getPassword());
            String nom = txtNombre1.getText();
            String rol = cbxRol.getSelectedItem().toString();
            String empresa_ruc = conf.getRuc();

            boolean c = isValid(correo);

            if (c == true) {
                lg.setNombre(nom);
                lg.setCorreo(correo);
                lg.setPass(pass);
                lg.setRol(rol);
                lg.setCedula(cedula);
                lg.setEmpresa_ruc(empresa_ruc);

                boolean r = login.Registrar(lg);

                if (r == true) {
                    JOptionPane.showMessageDialog(null, "Usuario Registrado");
                    sistema.nuevoUsuario();
                    Login si = new Login();
                    si.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario existente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Correo no valido");
            }

        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    //FUNCION PARA VALIDAR EL CORREO
    
    
    public static boolean isValid(String email) {
        String emailREGEX = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailREGEX);
        if (email == null) {
            return false;
        }
        return pattern.matcher((CharSequence) email).matches();
    }
    
    private void txtexit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexit1MouseClicked
        // TODO add your handling code here:

        Login sis = new Login();
        sis.setVisible(true);
        dispose();


    }//GEN-LAST:event_txtexit1MouseClicked

    private void txtexit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexit1MouseEntered
        // TODO add your handling code here:

        //btnexit.setBackground(Color.red);
    }//GEN-LAST:event_txtexit1MouseEntered

    private void txtexit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexit1MouseExited
        // TODO add your handling code here:
        //btnexit.setBackground(Color.white);
    }//GEN-LAST:event_txtexit1MouseExited

    private void btnexitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseDragged

        // TODO add your handling code here:
    }//GEN-LAST:event_btnexitMouseDragged

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnexitMouseClicked

    private void btnexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnexitMouseEntered

    private void btnexitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnexitMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_headerMousePressed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassKeyTyped

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
        if (txtCedula.getText().length() >= 10) {
            evt.consume();
            //JOptionPane.showMessageDialog(null, "Ha ingresado 1 digito mas lo establecido...");
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPass.requestFocus();
        }
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCedula.requestFocus();
        }
    }//GEN-LAST:event_txtPassKeyPressed

    private void txtNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txtNombre1KeyTyped

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNombre1.requestFocus();
        }
    }//GEN-LAST:event_txtCedulaKeyPressed

    private void txtNombre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCorreo.requestFocus();
        }
    }//GEN-LAST:event_txtNombre1KeyPressed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPRegistrar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel btnexit;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JLabel txtexit1;
    // End of variables declaration//GEN-END:variables

}
